import type { ProfileRecord, QuestionHistoryRecord, RunHistoryRecord, SetProgressRecord } from '../data/types';
import type { CuratedSetDefinition } from '../game';
import { formatDate, formatDuration, formatMoney } from '../utils/format';

interface CommonProps { playerName: string; onBack: () => void; }

export function StatisticsScreen({ profile, runs, questionHistory, playerName, onBack }: CommonProps & { profile: ProfileRecord | null; runs: readonly RunHistoryRecord[]; questionHistory: readonly QuestionHistoryRecord[] }) {
  const answered = runs.reduce((sum, run) => sum + run.correctCount + run.incorrectCount, 0);
  const correct = runs.reduce((sum, run) => sum + run.correctCount, 0);
  const averageReached = runs.length ? runs.reduce((sum, run) => sum + run.highestQuestion, 0) / runs.length : 0;
  const totalTime = runs.reduce((sum, run) => sum + run.durationMs, 0);
  const byLevel = Array.from({ length: 15 }, (_, index) => ({ level: index + 1, count: runs.filter((run) => run.highestQuestion >= index + 1).length }));
  return <main className="screen insights-screen" aria-labelledby="statistics-title"><InsightsHeader label="Career telemetry" title="Statistics" onBack={onBack} /><div className="insights-body screen-scroll"><span className="kicker">{playerName}</span><h1 id="statistics-title">Knowledge, measured.</h1><p className="hero-subtitle">Career figures are derived from idempotently committed local run records.</p><div className="stat-grid"><Metric label="Personal best" value={formatMoney(profile?.statistics.highestPrize ?? Math.max(0, ...runs.map((run) => run.payout)))} accent /><Metric label="Millionaire wins" value={String(profile?.statistics.millionaireWins ?? runs.filter((run) => run.outcome === 'millionaire').length)} /><Metric label="Runs completed" value={String(runs.length)} /><Metric label="Total winnings" value={formatMoney(profile?.statistics.totalVirtualWinnings ?? runs.reduce((sum, run) => sum + run.payout, 0))} /><Metric label="Answer accuracy" value={answered ? `${Math.round(correct / answered * 100)}%` : '—'} /><Metric label="Average question" value={runs.length ? averageReached.toFixed(1) : '—'} /><Metric label="Unique questions" value={String(questionHistory.length)} /><Metric label="Time played" value={formatDuration(totalTime)} /></div><section className="progress-panel panel"><div><span className="kicker">Prize ladder reach</span><h2>How far each run traveled</h2></div><div className="level-bars">{byLevel.map(({ level, count }) => <div key={level} title={`${count} run${count === 1 ? '' : 's'} reached Level ${level}`}><i style={{ height: `${runs.length ? Math.max(4, count / runs.length * 100) : 4}%` }} /><span>{level}</span></div>)}</div></section></div></main>;
}

export function HistoryScreen({ runs, playerName, onBack, onSelect }: CommonProps & { runs: readonly RunHistoryRecord[]; onSelect: (run: RunHistoryRecord) => void }) {
  return <main className="screen insights-screen" aria-labelledby="history-title"><InsightsHeader label="Durable local record" title="Run History" onBack={onBack} /><div className="insights-body screen-scroll"><span className="kicker">{playerName}</span><h1 id="history-title">Every completed ascent.</h1><p className="hero-subtitle">Question snapshots remain available even if a custom pack is later disabled or removed.</p>{runs.length ? <div className="history-table panel" role="table" aria-label="Completed runs"><div className="history-row history-row--header" role="row"><span>Date</span><span>Mode</span><span>Outcome</span><span>Reached</span><span>Payout</span><span /></div>{runs.map((run) => <button className="history-row" role="row" type="button" key={run.id} onClick={() => onSelect(run)}><span>{formatDate(run.completedAt)}</span><span>{run.setId ?? (run.mode === 'fresh-mix' ? 'Fresh Mix' : 'Curated set')}</span><span className={`outcome outcome--${run.outcome}`}>{run.outcome === 'millionaire' ? 'Millionaire' : run.outcome === 'walked-away' ? 'Walked away' : 'Incorrect'}</span><span>Q{run.highestQuestion}</span><strong>{formatMoney(run.payout)}</strong><span>Review →</span></button>)}</div> : <EmptyState title="No completed runs yet" copy="Your first result will appear here after a wrong answer, walk-away, or millionaire win." />}</div></main>;
}

export function SetProgressScreen({ sets, progress, playerName, onBack, onPlay }: CommonProps & { sets: readonly CuratedSetDefinition[]; progress: readonly SetProgressRecord[]; onPlay: (setId: string) => void }) {
  const byId = new Map(progress.map((entry) => [entry.setId, entry]));
  return <main className="screen insights-screen" aria-labelledby="sets-title"><InsightsHeader label="Authored challenges" title="Set Progress" onBack={onBack} /><div className="insights-body screen-scroll"><span className="kicker">{playerName}</span><h1 id="sets-title">{sets.length} distinct paths.</h1><p className="hero-subtitle">Curated question order stays fixed; answer positions reshuffle for each new attempt.</p><div className="set-progress-grid">{sets.map((set, index) => { const item = byId.get(set.id); return <article className={`set-progress-card panel ${item?.wins ? 'set-progress-card--won' : ''}`} key={set.id}><span className="set-progress-card__index">{String(index + 1).padStart(2, '0')}</span><span className="kicker">{set.theme || 'Mixed knowledge'}</span><h2>{set.title}</h2><p>{set.description}</p><dl><div><dt>Status</dt><dd>{item?.wins ? 'Millionaire won' : item?.attempts ? 'Attempted' : 'New'}</dd></div><div><dt>Attempts</dt><dd>{item?.attempts ?? 0}</dd></div><div><dt>Best result</dt><dd>{formatMoney(item?.bestPrize ?? 0)} · Q{item?.bestQuestion ?? 0}</dd></div></dl><button type="button" className="secondary-button" onClick={() => onPlay(set.id)}>{item?.attempts ? 'Play Again' : 'Begin Set'}</button></article>; })}</div></div></main>;
}

function InsightsHeader({ label, title, onBack }: { label: string; title: string; onBack: () => void }) { return <header className="utility-bar"><div><div className="utility-label">{label}</div><div className="utility-value">{title}</div></div><div className="utility-bar__spacer" /><button className="quiet-button" type="button" onClick={onBack}>← Dashboard</button></header>; }
function Metric({ label, value, accent = false }: { label: string; value: string; accent?: boolean }) { return <div className={`metric-card panel ${accent ? 'metric-card--accent' : ''}`}><span>{label}</span><strong>{value}</strong></div>; }
function EmptyState({ title, copy }: { title: string; copy: string }) { return <div className="empty-state panel"><span>◇</span><h2>{title}</h2><p>{copy}</p></div>; }
